name: Pack validation (strict)
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
      - 'tools/**'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'tools/**'
jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate pack (strict)
        uses: PopTracker/pack-checker-action@v1
        with:
          strict: true